### ISSUE TITLE
cannot use &array literal 

### ISSUE THREAD

**Issue by jtc25** [StepLg/go-graph#1]
when I use goinstall  it produces two errors: /go/src/pkg/github.com/StepLg/go-graph/src/graph/neighbours_extractor.go:50: cannot use &array literal (type *[2]iterable.Iterable) as type []iterable.Iterable in function argument.

Is there something wrong here or I'm I missing something?

I have a new Imac I5 and OS X 10.6.4

**Comment by StepLg** [comment]
yes, that's because I didn't fix go-graph for latest go release. Fix this as possible as i can (today or tomorrow)
